name: msme_borrower
description: MSME Digital Lending Sandbox — Borrower Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.2.1
  
  # State Management
  provider: ^6.1.2

  # Secure Storage (JWT token)
  flutter_secure_storage: ^9.2.2

  # Charts
  fl_chart: ^0.70.2

  # Google Fonts
  google_fonts: ^6.2.1

  # UI Extras
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
